<?php 
/**
 * @category Arun
 * @package Arun_CustomerProfile
 * @copyright Copyright (c) 2023 Arun
 * @author Arun
 */

?>
<legend class="legend">
    <span><?php echo __('Customer Profile') ?></span>
</legend>   
<div class="field customer_file_upload">
    <label for="customer_profile" class="label"><span><?php echo __('Profile Image') ?></span></label>
    <div class="control">
        <input type="file" name="customer_profile" id="customer_profile" title="<?php echo __('Custom Image') ?>" class="input-text" data-validate="{required:false}">
    </div>
</div>
