<?php 
/**
 * @category Arun
 * @package Arun_CustomerProfile
 * @copyright Copyright (c) 2023 Arun
 * @author Arun
 */

/**
 * @var Arun\CustomerProfile\Block\Customer\Account $block
 */
?>
<?php if ($url = $block->getFileUrl()): ?>
<strong class="box-title">
    <span>Profile Image</span>
</strong>
<div class="field">
    <img width="100" height="100" src="<?php echo $url ?>" alt="Profile Image" />
</div>
<?php endif;?>